version: '3.8'

services:
  zephyr-dex:
    image: nekrasovgfm/zephyr-dex:latest
    build:
      context: .
      dockerfile: Dockerfile
      platform: linux/amd64
    ports:
      - target: 3000
        published: 80
        protocol: tcp
        mode: host
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "health-check.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - zephyr-dex-network

networks:
  zephyr-dex-network:
    driver: bridge 